# Redirect all requests to index.html (for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ensure PDFs and other static files are served correctly
[[headers]]
  for = "/*.pdf"
  [headers.values]
    Content-Type = "application/pdf"
    Cache-Control = "public, max-age=31536000"
